### ISSUE TITLE
Unable to Load Example Data Sources with slow internet speed.

### ISSUE THREAD

**Issue by aditeyapandey** [vega/lyra#213]
Hi Arvind,

As we noticed during your visit at our lab that the example data sources sometimes do not load along with the application. The reason that you figured out was that there is timeout function which was loading the data files, therefore at times due to timeout function expiring cases where the internet speed is less the files may not load. I think you can take look at it. :)

**Comment by aoosapps** [comment]
Hit the same issue today, is there a way we can set up an extended timeout for vegajs?

**Comment by jonathanzong** [comment]
I think this is actually resolved in Lyra 2. Sorry for the notifications!
